### ISSUE TITLE
mostly useless

### ISSUE THREAD

**Issue by sotilism** [Yuvix25/kahoot-answer-bot#1]
So this is a very useful extension. But I sadly am not able to use this, since most of the kahoots I do aren't published. This wouldn't happen if it would just work like usually, use QuizId. So that's why I would appreciate it if you could help me locate or change the code to just type in the QuizId. Since I'm pretty trash at changing code I didn't make. Thank you

**Comment by Yuvix25** [comment]
@LukeeHax Sorry for the (massive 😅) delay, did not get an email for some reason.
Basically once you select the Kahoot in the sidebar, the function `loadKahoot(id)` is called (see `content.js`). So if I understand your question correctly, all you need to do is to add an input element to the HTML variable in `explorer.js`, have it listen for keyup events like I do [here](https://github.com/Yuvix25/kahoot-answer-bot/blob/33a9d54392f1d3c5f9f933a2c8d86a7688c665c6/js/content.js#L67) (note that I only listen for when enter is pressed, otherwise it will be called on each keystroke), and then call `loadKahoot` with its value.
Feel free to re-open if you need any help 🙂
