### ISSUE TITLE
buggy wuggy

### ISSUE THREAD

**Issue by billybobgaming** [Yuvix25/kahoot-answer-bot#2]
When you get the zip file you have to delete manifests and put manifests back in there

**Comment by Yuvix25** [comment]
Can you explain a bit more?
Works just fine for me.

**Comment by billybobgaming** [comment]
Idk why.   https://youtube.com/shorts/BPHeRNc4yOw?si=_C_lDudwDuzjla2t    I made a video

**Comment by billybobgaming** [comment]
Maybe just opera?

**Comment by Yuvix25** [comment]
Ok, I think I found the issue.
After you click on "Load Unpacked", you choose the folder, but then notice there's another folder named "kahoot-answer-bot-main" inside it. That's the one you need to choose.
I assume you have this duplicate folder inside folder because of some weird zip unpacking thing.

Please let me know if choosing the inner folder solves it, thanks.
